[project]
name = "prototypes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Kingsley Leon", email = "kingsleyleoncs@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "mediapipe==0.10.35",
    "opencv-python>=5.0.0.93",
]
  
[tool.uv.build-backend]
module-name = "app"


[project.scripts]
prototypes = "app:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
